### ISSUE TITLE
Export-CSV

### ISSUE THREAD

**Issue by samerrill613** [thezim/posh-stig#11]
What is the trick to exporting the STIG data results to a CSV?  I tried the Export-CSV cmdlet and end up with "System.Object[]" for Vulnerabilities.
Thanks

**Comment by thezim** [comment]
@samerrill613 Import-Checklist return an single object and Vulnerabilities is a property that is an array. Export-Csv will export a single row and return System.Object[] for Vulnerabilities. You will need to flatten the entire root object with something like this to use Export-Csv. You might have to be careful with some of the fields as the do contain carriage returns and new lines. Hope this helps.

``` Powershell
$checklist= Import-Checklist stig.ckl
$flat = @()
foreach($vuln in $checklist.Vulnerabilities) {
    $flat += [PSCustomObject]@{
        # general info
        Title = $checklist.Title
        Version = $checklist.Version
        # asset info
        AssetType = $checklist.Asset.AssetType
        HostIP = $checklist.Asset.HostIP
        HostMAC = $checklist.Asset.HostMAC
        HostName = $checklist.Asset.HostName
        Role = $checklist.Asset.Role
        TargetKey = $checklist.Asset.TargetKey
        Comments = $checklist.Asset.Comments
        # vulnerability
        FindingDetails =$vuln.FindingDetails
        SeverityJustification =$vuln.SeverityJustification
        SeverityOverride =$vuln.SeverityOverride
        Status =$vuln.Status
        CheckContent =$vuln.Data.CheckContent
        Check_Content_Ref =$vuln.Data.Check_Content_Ref
        Class =$vuln.Data.Class
        Documentable =$vuln.Data.Documentable
        FalseNegatives =$vuln.Data.FalseNegatives
        FalsePositives =$vuln.Data.FalsePositives
        FixText =$vuln.Data.FixText
        MitigationControl =$vuln.Data.MitigationControl
        Mitigations =$vuln.Data.Mitigations
        Potential_Impact =$vuln.Data.Potential_Impact
        Responsibility =$vuln.Data.Responsibility
        RuleId =$vuln.Data.RuleId
        RuleTitle =$vuln.Data.RuleTitle
        RuleVersion =$vuln.Data.RuleVersion
        STIGRef =$vuln.Data.STIGRef
        SecurityOverrideGuidance =$vuln.Data.SecurityOverrideGuidance
        Severity =$vuln.Data.Severity
        TargetKeyVuln =$vuln.Data.TargetKey
        ThirdPartyTools =$vuln.Data.ThirdPartyTools
        VulnDiscuss =$vuln.Data.VulnDiscuss
        VulnNumber =$vuln.Data.VulnNumber
    }
}
$flat | Export-Csv -NoTypeInformation -Path stig.csv
```

**Comment by samerrill613** [comment]
@thezim Thank you so very much for the quick response.  This is awesome and it worked perfectly.  Thanks also for the heads up on the carriage returns. I frequently need to export a large number of checklists to CSV using the STIGVIEWER which is quite time consuming.  Not to mention they didn't include the FIX_TEXT in the 2.x versions of the stigviewer.  This has me moving in the right direction.

**Comment by samerrill613** [comment]
@thezim I am able to convert a single checklist but when I try to pass multiple checklist files using the syntax in the readme.md I get the following error (note the ~ on the 2nd line lines up under the , :
+ $checklist= Import-Checklist -Path @(ckl\2.ckl, ckl\1.ckl)
+                                               ~
Missing argument in parameter list.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingArgument

If I put quotes around the checklist names I get the following error:
Import-Checklist : Cannot process argument transformation on parameter 'Path'. Cannot convert value to type System.String.
At C:\Users\merrills\Documents\STIG2CSV2.ps1:3 char:36
+ $checklist= Import-Checklist -Path @("ckl\2.ckl", "ckl\1.ckl")
+                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Import-Checklist], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Import-Checklist

**Comment by thezim** [comment]
Move to new issue. Closing Export-Csv issue.
