### ISSUE TITLE
Expose properties to the parent object

### ISSUE THREAD

**Issue by krylon** [thezim/posh-stig#8]
You have to go digging pretty deep to get some info. Would it be worthwhile to expose some properties at the top level?

**Comment by thezim** [comment]
The current structure mimics what is in the checklist format. Prior to 5aceeebdf997690c59f28eb3724871e042fa8d9b it was entirely flat, aka CSV ready. I wasn't entirely pleased with the level of nested objects but it is logical and easy to follow. I also thought converting back to a checklist might be easier if the format was structured the same. What changes would you recommend?

**Comment by krylon** [comment]
The only thing that comes to mind is possibly status counts like Not Reviewed, Closed, etc. Perhaps in a ScriptProperty?

**Comment by krylon** [comment]
The more I think about it I suppose its unnecessary, if you're familiar with how to navigate the properties you can gather this info. My thoughts were more in line with someone who is not familiar with how to dig through a PowerShell object.

**Comment by thezim** [comment]
A ScriptMethod would not survive an Export-Csv, ConvertTo-Html, or ConvertTo-Json. I think is see where you are are going in providing the visibility that the stig viewer does. My goal was to simple get the information out into other formats for aggregation. I think another cmdlet (function) to get the count would be a better idea than messing with the base object. Thoughts?

**Comment by krylon** [comment]
I think i'll leave it alone for now. I agree that another exported cmdlet would be better. I haven't convinced myself enough that it's necessary though.

**Comment by thezim** [comment]
Closing issue.
