### ISSUE TITLE
Update README.md with module help.

### ISSUE THREAD

**Issue by thezim** [thezim/posh-stig#9]
The README should have the output of one of the help posh-stig levels.

**Comment by krylon** [comment]
Something like [this example](https://gist.github.com/jxson/1784669) perhaps?

**Comment by thezim** [comment]
Updated with Get-Help -Detailed output bf43c52169a8984ef1bcfb1895f3c2075d1cdcbf for now.

**Comment by thezim** [comment]
Something [simpler](https://gist.github.com/zenorocha/4526327)?

**Comment by thezim** [comment]
Updated README with 220a9b9c22822e767e95a91de205e395afc5970e. Closing issue.
